### ISSUE TITLE
Quorum post-upgrade template

### ISSUE THREAD

**Issue by boldis** [PharmaLedger-IMI/helm-charts#113]
I believe that namespace definition in post-upgrade should evaluate to release namespace not defautl:

Original version:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quorum-propose-rb
  namespace: {{ default .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    "helm.sh/hook-weight": "30"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quorum-propose-cr
subjects:
  - kind: ServiceAccount
    name: quorum-propose-service-account
    namespace: default

```
Proposed fix:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quorum-propose-rb
  namespace: {{ default .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
    "helm.sh/hook-weight": "30"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quorum-propose-cr
subjects:
  - kind: ServiceAccount
    name: quorum-propose-service-account
    namespace: {{ default .Release.Namespace }}

```
